(() => {
  "use strict";

  const KEY = "sowiaSzklarniaSave";
  const VERSION = 1;
  const core = window.SowieCore;
  const $ = (id) => document.getElementById(id);
  const canvas = $("greenhouseCanvas");
  const ctx = canvas.getContext("2d");
  const panel = $("panelContent");
  const tabs = $("tabBar");
  const logNode = $("greenhouseLog");
  const offlineModal = $("offlineModal");
  const offlineText = $("offlineText");
  const resetModal = $("resetModal");
  const hud = {
    leaves: $("leavesValue"), lps: $("lpsValue"), water: $("waterValue"), seeds: $("seedsValue"),
    pollen: $("pollenValue"), goats: $("goatsValue"), compost: $("compostValue"), joy: $("joyValue"), save: $("saveValue"),
  };

  const TABS = [["build", "Budowa", "🏗️"], ["plants", "Rośliny", "🌿"], ["cross", "Krzyżuj", "🧬"], ["goats", "Kozy", "🐐"], ["research", "Badania", "🔬"], ["stats", "Staty", "📊"]];
  const ROOMS = [
    { id: "potting", icon: "🪴", name: "Doniczarnia", desc: "Podstawowe sadzenie i spokojny start.", leaves: 35, water: 0, slots: 2, leaf: .05, grow: .08 },
    { id: "grow", icon: "🌿", name: "Sala Upraw", desc: "Więcej miejsc i więcej liści.", leaves: 180, water: 10, slots: 4, leaf: .22, grow: .1 },
    { id: "water", icon: "💧", name: "Zraszalnia", desc: "Produkuje wodę i pomaga roślinom rosnąć.", leaves: 260, water: 0, slots: 1, wps: .45, grow: .08 },
    { id: "seedling", icon: "🌱", name: "Sadzonkarnia", desc: "Produkuje nasiona do kolejnych sadzeń.", leaves: 540, water: 45, slots: 2, sps: .035 },
    { id: "cross", icon: "🧬", name: "Krzyżówkarium", desc: "Pozwala krzyżować dojrzałe rośliny.", leaves: 1600, water: 140, slots: 2, pps: .04 },
    { id: "pollen", icon: "🔬", name: "Laboratorium Pyłku", desc: "Dodatkowy pyłek i lepsze hybrydy.", leaves: 2400, water: 220, slots: 1, pps: .1 },
    { id: "compost", icon: "🪱", name: "Kompostownia", desc: "Produkuje kompost i pomaga po kozach.", leaves: 1200, water: 60, slots: 1, cps: .03 },
    { id: "fence", icon: "🎀", name: "Płotek Antykozi", desc: "Mniej kóz. Więcej kokardek.", leaves: 900, water: 90, slots: 0, antiGoat: .25 },
    { id: "command", icon: "🦉", name: "Sowie Centrum", desc: "Automatyzacja zbiorów i podlewania.", leaves: 5200, water: 360, slots: 1, auto: 1 },
    { id: "nap", icon: "🌙", name: "Kącik Drzemki", desc: "Radość sowy i lepszy offline progress.", leaves: 3600, water: 200, slots: 1, offline: .25 },
  ];
  const PLANTS = [
    { id: "monstera", icon: "🌿", name: "Monstera Miziasta", desc: "Tania, puchata i startowa.", seeds: 1, water: 2, prod: .45, pollen: .004, grow: 26, goat: 1, color: "#55a96b" },
    { id: "pilea", icon: "🪴", name: "Pilea Pieniążek", desc: "Dobra ekonomia na początek.", seeds: 2, water: 4, prod: 1.25, pollen: .006, grow: 42, goat: 1.15, color: "#72bd68" },
    { id: "fern", icon: "🌱", name: "Paproć Puchata", desc: "Więcej pyłku do krzyżowania.", seeds: 3, water: 12, prod: 3.8, pollen: .03, grow: 80, goat: 1.35, unlock: 350, color: "#4b9e72" },
    { id: "alocasia", icon: "🍃", name: "Alokazja Sówkowa", desc: "Mocna, ale smaczna dla kóz.", seeds: 5, water: 22, prod: 9.5, pollen: .018, grow: 115, goat: 1.7, unlock: 1200, color: "#417b64" },
    { id: "cactus", icon: "🌵", name: "Kaktus Pracu", desc: "Mało pije i daje kompost.", seeds: 8, water: 8, prod: 18, pollen: .01, compost: .012, grow: 160, goat: .75, unlock: 3500, color: "#5ba760" },
    { id: "orchid", icon: "🌸", name: "Storczyk Pluskowy", desc: "Piękny, pyłkowy i ryzykowny.", seeds: 10, water: 55, prod: 42, pollen: .06, grow: 210, goat: 2.1, unlock: 9000, color: "#d96faf" },
    { id: "monpilea", icon: "🌿", name: "Monpilea Przytulna", desc: "Hybryda Monstery i Pilei.", seeds: 12, water: 45, prod: 78, pollen: .05, grow: 190, goat: 1.5, hybrid: true, color: "#68c582" },
    { id: "alopaproc", icon: "🍀", name: "Alopaproć Wachlarzowa", desc: "Pyłkowa hybryda wachlarzowa.", seeds: 16, water: 70, prod: 150, pollen: .11, grow: 260, goat: 1.8, hybrid: true, color: "#3fa976" },
    { id: "goldleaf", icon: "🍂", name: "Złotolistka", desc: "Rzadka hybryda i kozi magnes.", seeds: 26, water: 120, prod: 430, pollen: .16, grow: 360, goat: 3, hybrid: true, color: "#caa34a" },
  ];
  const RECIPES = [
    { id: "monpilea", icon: "🌿", parents: ["monstera", "pilea"], result: "monpilea", water: 35, pollen: 16, seconds: 70, chance: .78 },
    { id: "alopaproc", icon: "🍀", parents: ["fern", "alocasia"], result: "alopaproc", water: 70, pollen: 42, seconds: 120, chance: .62 },
    { id: "goldleaf", icon: "🍂", parents: ["monpilea", "alopaproc"], result: "goldleaf", water: 180, pollen: 140, seconds: 220, chance: .34 },
  ];
  const RESEARCH = [
    { id: "botany", branch: "Botanika", icon: "🌿", name: "Miękkie etykietki", desc: "+20% liści.", cost: { leaves: 280, pollen: 4 } },
    { id: "growth", branch: "Botanika", icon: "🌱", name: "Ciepłe półki", desc: "+25% wzrostu.", req: ["botany"], cost: { leaves: 1300, pollen: 20 } },
    { id: "water", branch: "Hydraulika cute", icon: "💧", name: "Różowe rurki", desc: "+30% wody.", cost: { leaves: 600, water: 60 } },
    { id: "goats", branch: "Antykozia taktyka", icon: "🎀", name: "Płotek z kokardką", desc: "Kozy pojawiają się rzadziej.", cost: { leaves: 950, compost: 5 } },
    { id: "sio", branch: "Antykozia taktyka", icon: "📣", name: "Dzwoneczek SIO", desc: "Lepsze nagrody za SIO!", req: ["goats"], cost: { leaves: 2200, compost: 14 } },
    { id: "auto", branch: "Organizacja sowy", icon: "🦉", name: "Sowie dyżury", desc: "Małe auto-zbiory.", cost: { leaves: 1800, pollen: 24 } },
    { id: "autoWater", branch: "Organizacja sowy", icon: "💦", name: "Sowa podlewa sama", desc: "Automatyczne podlewanie.", req: ["auto", "water"], cost: { leaves: 4200, water: 180, pollen: 40 } },
    { id: "offline", branch: "Organizacja sowy", icon: "🌙", name: "Drzemka z notesem", desc: "+30% offline progress.", cost: { leaves: 5000, compost: 18 } },
  ];

  let state = load();
  let tab = "build", dirty = true, last = performance.now(), saveTimer = 0, renderTimer = 0, autoWaterTimer = 0;
  let meter = null, particles = [], texts = [], speech = null;

  function id(prefix) { return `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`; }
  function defaultSave() { const now = Date.now(); const room = id("room"); return { version: VERSION, createdAt: now, lastSavedAt: now, leaves: 25, water: 20, seeds: 6, pollen: 0, compost: 0, owlJoy: 55, lifetimeLeaves: 25, lifetimeWater: 20, grid: { floors: 2, columns: 3 }, rooms: [{ id: room, type: "potting", x: 1, y: 1, level: 1, builtAt: now }], plants: [{ uid: id("plant"), plantId: "monstera", roomId: room, growth: 1, health: 100, traits: { smell: "boring", growth: "normal" } }], discovered: ["monstera", "pilea"], crossbreeds: [], goats: [], nextGoatAt: now + 65000, research: {}, automation: {}, effects: { watered: 0 }, stats: { clicks: 0, roomsBuilt: 1, plantsPlanted: 1, crossbreeds: 0, hybrids: 0, goatsScared: 0, goatLoss: 0, offlineLeaves: 0, offlineWater: 0, bestLps: 0 }, achievements: {} }; }
  function mergeSave(raw) { const base = defaultSave(); if (!raw || typeof raw !== "object") return base; const merged = { ...base, ...raw, grid: { ...base.grid, ...(raw.grid || {}) }, research: { ...base.research, ...(raw.research || {}) }, automation: { ...base.automation, ...(raw.automation || {}) }, effects: { ...base.effects, ...(raw.effects || {}) }, stats: { ...base.stats, ...(raw.stats || {}) }, achievements: { ...base.achievements, ...(raw.achievements || {}) }, rooms: Array.isArray(raw.rooms) ? raw.rooms : base.rooms, plants: Array.isArray(raw.plants) ? raw.plants : base.plants, discovered: Array.isArray(raw.discovered) ? raw.discovered : base.discovered, crossbreeds: Array.isArray(raw.crossbreeds) ? raw.crossbreeds : base.crossbreeds, goats: Array.isArray(raw.goats) ? raw.goats : [], version: VERSION }; for (const plant of merged.plants) { plant.health = Number.isFinite(plant.health) ? plant.health : 100; plant.traits ||= { smell: "normal", growth: "normal" }; } return merged; }
  function load() { try { return mergeSave(JSON.parse(localStorage.getItem(KEY) || "null")); } catch (_error) { return defaultSave(); } }
  function save(reason = "auto") { state.lastSavedAt = Date.now(); try { localStorage.setItem(KEY, JSON.stringify(state)); hud.save.textContent = reason === "manual" ? "Zapisano ręcznie" : "Zapisano"; core?.recordStat?.("szklarniaLeaves", state.lifetimeLeaves, "max"); core?.recordStat?.("szklarniaRooms", state.rooms.length, "max"); } catch (_error) { hud.save.textContent = "Błąd zapisu"; log("Nie udało się zapisać gry w localStorage."); } }
  function queueSave(reason = "auto") { hud.save.textContent = "Zapisywanie…"; clearTimeout(saveTimer); saveTimer = setTimeout(() => save(reason), 280); }

  const fmt = (value) => { if (!Number.isFinite(value)) return "0"; if (Math.abs(value) < 1000) return value < 10 && value % 1 ? value.toFixed(1) : String(Math.floor(value)); const suffix = ["", "K", "M", "B", "T", "Qa", "Qi"]; let i = 0, n = Math.abs(value); while (n >= 1000 && i < suffix.length - 1) { n /= 1000; i++; } return `${value < 0 ? "-" : ""}${n.toFixed(n >= 100 ? 0 : n >= 10 ? 1 : 2).replace(/\.0+$/, "")}${suffix[i]}`; };
  const time = (s) => s >= 3600 ? `${Math.floor(s / 3600)}h ${Math.floor(s % 3600 / 60)}m` : s >= 60 ? `${Math.floor(s / 60)}m ${Math.floor(s % 60)}s` : `${Math.floor(s)}s`;
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const roomType = (id) => ROOMS.find((x) => x.id === id);
  const plantType = (id) => PLANTS.find((x) => x.id === id);
  const roomById = (id) => state.rooms.find((x) => x.id === id);
  const plantByUid = (uid) => state.plants.find((x) => x.uid === uid);
  const hasRoom = (type) => state.rooms.some((r) => r.type === type);
  const hasResearch = (id) => Boolean(state.research[id]);
  const log = (msg) => { logNode.textContent = msg; };
  const addLeaves = (n) => { state.leaves += n; state.lifetimeLeaves += Math.max(0, n); };
  const addWater = (n) => { state.water += n; state.lifetimeWater += Math.max(0, n); };
  function costLabel(cost) { return Object.entries(cost).filter(([, v]) => v > 0).map(([k, v]) => `${fmt(v)} ${{ leaves: "liści", water: "wody", pollen: "pyłku", compost: "kompostu", seeds: "nasion" }[k] || k}`).join(" · ") || "gratis"; }
  function canAfford(cost) { return Object.entries(cost).every(([k, v]) => (state[k] || 0) >= v); }
  function spend(cost) { if (!canAfford(cost)) return false; for (const [k, v] of Object.entries(cost)) state[k] -= v; return true; }

  function roomCost(type) { const n = state.rooms.filter((r) => r.type === type.id).length; return { leaves: Math.floor(type.leaves * Math.pow(1.24, n)), water: Math.floor((type.water || 0) * Math.pow(1.16, n)) }; }
  function upgradeCost(room) { const type = roomType(room.type); return { leaves: Math.floor(type.leaves * Math.pow(room.level + 1, 2.05)), water: Math.floor((type.water + 12) * Math.pow(room.level + 1, 1.55)) }; }
  function nextSlot() { const used = new Set(state.rooms.map((r) => `${r.x}:${r.y}`)); for (let y = state.grid.floors - 1; y >= 0; y--) for (let x = 0; x < state.grid.columns; x++) if (!used.has(`${x}:${y}`)) return { x, y }; return null; }
  function plantsInRoom(roomId) { return state.plants.filter((p) => p.roomId === roomId); }
  function slots() { return state.rooms.reduce((sum, r) => sum + (roomType(r.type)?.slots || 0) + Math.max(0, r.level - 1), 0); }
  function freeRoom() { return state.rooms.find((r) => plantsInRoom(r.id).length < ((roomType(r.type)?.slots || 0) + Math.max(0, r.level - 1))); }

  function metrics() {
    let leaf = 1, grow = 1, wps = 0, sps = 0, pps = 0, cps = 0, antiGoat = 0, offline = .35, cap = 7200;
    for (const room of state.rooms) { const t = roomType(room.type), m = 1 + (room.level - 1) * .5; leaf += (t.leaf || 0) * m; grow += (t.grow || 0) * m; wps += (t.wps || 0) * m; sps += (t.sps || 0) * m; pps += (t.pps || 0) * m; cps += (t.cps || 0) * m; antiGoat += (t.antiGoat || 0) * m; offline += (t.offline || 0) * m; }
    if (hasResearch("botany")) leaf *= 1.2; if (hasResearch("growth")) grow *= 1.25; if (hasResearch("water")) wps *= 1.3; if (hasResearch("goats")) antiGoat += .25; if (hasResearch("offline")) { offline += .3; cap += 10800; } if (state.effects.watered > Date.now()) { leaf *= 1.8; grow *= 1.35; }
    let lps = 0, attraction = 0;
    for (const p of state.plants) { const t = plantType(p.plantId), r = roomById(p.roomId); if (!t || !r) continue; const m = clamp(p.growth, .15, 1) * clamp(p.health / 100, .25, 1) * (1 + (r.level - 1) * .35) * (p.traits.smell === "tasty" ? 1.1 : p.traits.smell === "irresistible" ? 1.2 : 1); lps += t.prod * m * leaf; if (p.growth >= 1) { pps += t.pollen || 0; cps += t.compost || 0; } attraction += t.goat * (p.growth >= 1 ? 1 : .35) * (p.traits.smell === "boring" ? .8 : p.traits.smell === "tasty" ? 1.35 : p.traits.smell === "irresistible" ? 1.9 : 1); }
    lps *= .85 + clamp(state.owlJoy, 0, 100) / 300; if (state.goats.some((g) => g.state === "nibbling")) lps *= .92;
    return { lps, wps, sps, pps, cps, grow, click: Math.max(1, 1 + lps * .08), antiGoat: clamp(antiGoat, 0, .9), goatRisk: clamp(attraction / 22 - antiGoat * .5, .05, 2.5), offline: clamp(offline, .25, 1.5), cap, autoHarvest: hasResearch("auto") || state.automation.autoHarvest, autoWater: hasResearch("autoWater") || state.automation.autoWater };
  }

  function buildRoom(typeId) { const type = roomType(typeId), slot = nextSlot(); if (!slot) return log("Brak wolnych pól. Rozbuduj szklarnię."); const cost = roomCost(type); if (!spend(cost)) return log(`Brakuje zasobów: ${costLabel(cost)}.`); state.rooms.push({ id: id("room"), type: type.id, x: slot.x, y: slot.y, level: 1, builtAt: Date.now() }); state.stats.roomsBuilt++; log(`Zbudowano: ${type.name}.`); burst((slot.x + .5) / state.grid.columns, (slot.y + .5) / state.grid.floors, 24, "#4faf68"); core?.play?.("unlock"); dirty = true; queueSave("build"); }
  function upgradeRoom(roomId) { const room = roomById(roomId), cost = upgradeCost(room); if (!spend(cost)) return log(`Za mało zasobów: ${costLabel(cost)}.`); room.level++; log(`${roomType(room.type).name} ma poziom ${room.level}.`); dirty = true; queueSave("upgrade"); }
  function expandGrid() { const cost = { leaves: Math.floor(900 * Math.pow(1.75, state.grid.columns + state.grid.floors - 5)), water: Math.floor(80 * Math.pow(1.4, state.grid.floors - 2)) }; if (state.grid.columns >= 6 && state.grid.floors >= 4) return log("Szklarnia ma maksymalny rozmiar MVP."); if (!spend(cost)) return log(`Rozbudowa wymaga: ${costLabel(cost)}.`); if (state.grid.columns < 6) state.grid.columns++; else state.grid.floors++; log("Szklarnia jest większa. Sowa zatwierdza projekt."); dirty = true; queueSave("expand"); }
  function unlockedPlant(p) { return !p.hybrid && state.lifetimeLeaves >= (p.unlock || 0) || state.discovered.includes(p.id); }
  function refreshUnlocks() { for (const p of PLANTS) if (!p.hybrid && state.lifetimeLeaves >= (p.unlock || 0) && !state.discovered.includes(p.id)) { state.discovered.push(p.id); log(`Nowy gatunek: ${p.name}.`); } }
  function plantSeed(plantId) { const type = plantType(plantId), room = freeRoom(); if (!type || !unlockedPlant(type)) return log("Ten gatunek nie jest jeszcze odkryty."); if (!room) return log("Brak wolnego miejsca na roślinę."); if (state.seeds < type.seeds || state.water < type.water) return log(`Sadzenie wymaga ${type.seeds} nasion i ${type.water} wody.`); state.seeds -= type.seeds; state.water -= type.water; state.plants.push({ uid: id("plant"), plantId, roomId: room.id, growth: .05, health: 100, traits: { growth: Math.random() < .18 ? "fast" : Math.random() < .18 ? "slow" : "normal", smell: type.goat > 2 ? "tasty" : Math.random() < .25 ? "tasty" : "normal" } }); state.stats.plantsPlanted++; log(`Sowa zasadziła: ${type.name}.`); dirty = true; queueSave("plant"); }
  function mature(plantId) { return state.plants.some((p) => p.plantId === plantId && p.growth >= 1); }
  function canCross(recipe) { return hasRoom("cross") && recipe.parents.every(mature) && state.water >= recipe.water && state.pollen >= recipe.pollen; }
  function startCross(recipeId) { const recipe = RECIPES.find((r) => r.id === recipeId); if (!recipe) return; if (!hasRoom("cross")) return log("Najpierw zbuduj Krzyżówkarium."); if (!recipe.parents.every(mature)) return log("Potrzebujesz dojrzałych rodziców."); if (state.water < recipe.water || state.pollen < recipe.pollen) return log("Brakuje wody albo pyłku."); state.water -= recipe.water; state.pollen -= recipe.pollen; state.crossbreeds.push({ id: id("cross"), recipeId, startedAt: Date.now(), duration: recipe.seconds }); state.stats.crossbreeds++; log("Krzyżowanie rozpoczęte."); dirty = true; queueSave("cross"); }
  function resolveCrosses() { const now = Date.now(); for (const c of [...state.crossbreeds]) { const r = RECIPES.find((x) => x.id === c.recipeId); if (!r || now - c.startedAt < r.duration * 1000) continue; const ok = Math.random() < Math.min(.95, r.chance + (hasRoom("pollen") ? .08 : 0) + (hasResearch("growth") ? .08 : 0)); if (ok) { if (!state.discovered.includes(r.result)) { state.discovered.push(r.result); state.stats.hybrids++; log(`Nowa hybryda: ${plantType(r.result).name}!`); } else log("Krzyżowanie dało więcej nasion hybrydowych."); state.seeds += r.result === "goldleaf" ? 2 : 4; burst(.5, .45, 42, plantType(r.result).color); } else { state.seeds += 1; state.compost += 2; log("Krzyżowanie nie wyszło idealnie, ale sowa odzyskała materiał."); } state.crossbreeds = state.crossbreeds.filter((x) => x.id !== c.id); dirty = true; queueSave("crossDone"); } }

  function spawnGoat(force = false) { const m = meter || metrics(), now = Date.now(); if (!force && now < state.nextGoatAt) return; const candidates = state.plants.filter((p) => p.growth >= .4); if (!candidates.length || state.goats.filter((g) => g.state !== "fleeing").length >= 3) { state.nextGoatAt = now + 60000; return; } const target = candidates[Math.floor(Math.random() * candidates.length)], room = roomById(target.roomId) || state.rooms[0]; state.goats.push({ id: id("goat"), roomId: room.id, target: target.uid, state: "nibbling", age: 0, dps: Math.max(.25, m.lps * .055), fleeUntil: 0 }); state.nextGoatAt = now + (50000 + Math.random() * 45000) / Math.max(.55, m.goatRisk) * (1 + m.antiGoat); log("Koza weszła do szklarni i wygląda podejrzanie niewinnie."); dirty = true; queueSave("goat"); }
  function updateGoats(delta) { const now = Date.now(); for (const g of state.goats) { if (g.state === "fleeing") continue; const p = plantByUid(g.target); if (!p) { g.state = "fleeing"; g.fleeUntil = now + 600; continue; } const loss = g.dps * delta; state.leaves = Math.max(0, state.leaves - loss); state.stats.goatLoss += loss; p.health = clamp(p.health - delta * 1.6, 15, 100); g.age += delta; state.owlJoy = clamp(state.owlJoy - delta * .03, 0, 100); if (g.age > 34) { g.state = "fleeing"; g.fleeUntil = now + 900; log("Koza podgryzła liście i uciekła z miną niewiniątka."); } } state.goats = state.goats.filter((g) => g.state !== "fleeing" || now < g.fleeUntil); }
  function scareGoat(goatId) { const g = goatId ? state.goats.find((x) => x.id === goatId) : state.goats.find((x) => x.state !== "fleeing"); if (!g) return log("Na razie nie ma kozy. Podejrzany spokój."); const room = roomById(g.roomId) || state.rooms[0], bonus = hasResearch("sio") ? 1.45 : 1, m = meter || metrics(); g.state = "fleeing"; g.fleeUntil = Date.now() + 1050; state.stats.goatsScared++; state.owlJoy = clamp(state.owlJoy + 2.5, 0, 100); speech = { text: "SIO! SIO!", x: (room.x + .5) / state.grid.columns, y: (room.y + .22) / state.grid.floors, until: Date.now() + 1300 }; const roll = Math.random(); if (roll < .68) addLeaves(Math.max(8, m.lps * 12) * bonus); else if (roll < .88) state.compost += 2 * bonus; else state.seeds += Math.ceil(bonus); burst(speech.x, speech.y + .1, 30, "#ffb1c7"); log("SIO! SIO! Koza uciekła aż jej kopytka zamigotały."); core?.play?.("goat"); dirty = true; queueSave("sio"); }
  function buyResearch(researchId) { const r = RESEARCH.find((x) => x.id === researchId); if (!r || hasResearch(r.id)) return; if ((r.req || []).some((req) => !hasResearch(req))) return log("Najpierw kup poprzednie badania."); if (!spend(r.cost)) return log(`Badanie wymaga: ${costLabel(r.cost)}.`); state.research[r.id] = Date.now(); if (r.id === "auto") state.automation.autoHarvest = true; if (r.id === "autoWater") state.automation.autoWater = true; log(`Badanie ukończone: ${r.name}.`); dirty = true; queueSave("research"); }

  function tick(delta) { meter = metrics(); addLeaves(meter.lps * delta); addWater(meter.wps * delta); state.seeds += meter.sps * delta; state.pollen += meter.pps * delta; state.compost += meter.cps * delta; if (meter.autoHarvest) addLeaves(meter.click * .25 * delta); for (const p of state.plants) { const t = plantType(p.plantId), speed = p.traits.growth === "fast" ? 1.22 : p.traits.growth === "slow" ? .86 : 1; if (p.growth < 1) p.growth = clamp(p.growth + delta / t.grow * meter.grow * speed, 0, 1); else if (p.health < 100 && state.effects.watered > Date.now()) p.health = clamp(p.health + delta * .5, 0, 100); } autoWaterTimer += delta; if (meter.autoWater && autoWaterTimer > 55 && state.water > Math.max(20, state.plants.length * 4)) { waterAll(false); autoWaterTimer = 0; } refreshUnlocks(); resolveCrosses(); spawnGoat(false); updateGoats(delta); state.stats.bestLps = Math.max(state.stats.bestLps, meter.lps); checkAchievements(); }
  function manualClick() { const m = meter || metrics(); addLeaves(m.click); state.stats.clicks++; pop(`+${fmt(m.click)}`, .5, .38, "#4faf68"); burst(.5, .42, 10, "#8fd36b"); dirty = true; }
  function waterAll(manual = true) { const cost = Math.max(8, Math.ceil(state.plants.length * 3)); if (state.water < cost) { if (manual) log(`Za mało wody. Potrzeba ${cost}.`); return false; } state.water -= cost; state.effects.watered = Date.now() + 40000; for (const p of state.plants) p.health = clamp(p.health + 16, 0, 100); if (manual) { log("Sowa podlała całą szklarnię. Produkcja rośnie."); burst(.52, .36, 24, "#55c7dd"); queueSave("water"); } dirty = true; return true; }
  function offline() { const elapsed = Math.max(0, (Date.now() - (state.lastSavedAt || Date.now())) / 1000); if (elapsed < 60) return; const m = metrics(), used = Math.min(elapsed, m.cap), leaves = m.lps * used * m.offline, water = m.wps * used * Math.min(1, m.offline * .75), seeds = m.sps * used * .7, pollen = m.pps * used * .65, compost = m.cps * used * .65, goatLoss = leaves * Math.min(.18, Math.max(0, m.goatRisk - m.antiGoat) * .035); addLeaves(Math.max(0, leaves - goatLoss)); addWater(water); state.seeds += seeds; state.pollen += pollen; state.compost += compost; state.stats.offlineLeaves += Math.max(0, leaves - goatLoss); state.stats.offlineWater += water; for (const p of state.plants) { const t = plantType(p.plantId); if (p.growth < 1) p.growth = clamp(p.growth + used / t.grow * m.grow * .6, 0, 1); } offlineText.innerHTML = `Sowa doglądała szklarni przez <strong>${time(elapsed)}</strong>.<br>Zebrano <strong>${fmt(Math.max(0, leaves - goatLoss))}</strong> liści, <strong>${fmt(water)}</strong> wody, <strong>${fmt(seeds)}</strong> nasion i <strong>${fmt(pollen)}</strong> pyłku.<br>${goatLoss > 0 ? `Kozy próbowały podgryzać liście, ale straty ograniczono do <strong>${fmt(goatLoss)}</strong>.` : "Kozy nie odważyły się wejść do środka."}`; offlineModal.hidden = false; save("offline"); }
  function checkAchievements() { const list = [["firstPlant", state.plants.length >= 2], ["rooms5", state.rooms.length >= 5], ["sio", state.stats.goatsScared >= 1], ["goats25", state.stats.goatsScared >= 25], ["cross", state.stats.crossbreeds >= 1], ["hybrid", state.stats.hybrids >= 1], ["big", state.grid.floors >= 4], ["gold", state.discovered.includes("goldleaf")]]; for (const [key, ok] of list) if (ok && !state.achievements[key]) state.achievements[key] = Date.now(); }

  function render() { tabs.innerHTML = TABS.map(([id, label, icon]) => `<button type="button" data-tab="${id}" class="${tab === id ? "is-active" : ""}"><span>${icon}</span>${label}</button>`).join(""); if (tab === "build") renderBuild(); else if (tab === "plants") renderPlants(); else if (tab === "cross") renderCross(); else if (tab === "goats") renderGoats(); else if (tab === "research") renderResearch(); else renderStats(); }
  function renderBuild() { const slot = nextSlot(), expand = { leaves: Math.floor(900 * Math.pow(1.75, state.grid.columns + state.grid.floors - 5)), water: Math.floor(80 * Math.pow(1.4, state.grid.floors - 2)) }; panel.innerHTML = `<div class="panel-intro"><strong>Buduj pokoje jak w przekroju cute schronu.</strong><span>Nowe pokoje trafiają w najbliższe wolne pole. Ulepszenia zwiększają wydajność i sloty.</span></div><div class="data-table"><div><span>Rozmiar</span><strong>${state.grid.columns}×${state.grid.floors}</strong></div><div><span>Miejsca</span><strong>${state.plants.length}/${slots()}</strong></div></div><div class="button-row"><button data-expand ${state.grid.columns >= 6 && state.grid.floors >= 4 ? "disabled" : ""}>Rozbuduj · ${costLabel(expand)}</button><button data-save>Zapisz teraz</button></div><h3 class="section-title">Pomieszczenia</h3><div class="grid">${ROOMS.map((t) => { const c = roomCost(t); return `<article class="card"><div class="card-title"><span>${t.icon}</span><strong>${t.name}</strong><em>${state.rooms.filter((r) => r.type === t.id).length}</em></div><p>${t.desc}</p><div class="mini-table"><span>Koszt</span><strong>${costLabel(c)}</strong><span>Sloty</span><strong>${t.slots}</strong></div><button data-build="${t.id}" ${!slot || !canAfford(c) ? "disabled" : ""}>Buduj</button></article>`; }).join("")}</div><h3 class="section-title">Zbudowane</h3><div class="grid compact">${state.rooms.map((r) => { const t = roomType(r.type), c = upgradeCost(r); return `<article class="card"><div class="card-title"><span>${t.icon}</span><strong>${t.name}</strong><em>poz. ${r.level}</em></div><div class="mini-table"><span>Pozycja</span><strong>${r.x + 1}:${state.grid.floors - r.y}</strong><span>Rośliny</span><strong>${plantsInRoom(r.id).length}/${(t.slots || 0) + Math.max(0, r.level - 1)}</strong><span>Ulepsz</span><strong>${costLabel(c)}</strong></div><button data-upgrade="${r.id}" ${!canAfford(c) ? "disabled" : ""}>Ulepsz</button></article>`; }).join("")}</div>`; }
  function renderPlants() { const free = slots() - state.plants.length; panel.innerHTML = `<div class="panel-intro"><strong>Sadź rośliny i odkrywaj gatunki.</strong><span>Dojrzałe rośliny produkują pełne liście, pyłek i czasem kompost.</span></div><div class="data-table"><div><span>Wolne miejsca</span><strong>${free}</strong></div><div><span>Dojrzałe</span><strong>${state.plants.filter((p) => p.growth >= 1).length}</strong></div><div><span>Odkryte</span><strong>${state.discovered.length}/${PLANTS.length}</strong></div></div><div class="grid">${PLANTS.map((p) => { const open = unlockedPlant(p); return `<article class="card ${open ? "" : "is-locked"}"><div class="card-title"><span>${p.icon}</span><strong>${p.name}</strong><em>${state.plants.filter((x) => x.plantId === p.id).length}</em></div><p>${p.desc}</p><div class="mini-table"><span>Produkcja</span><strong>${fmt(p.prod)}/s</strong><span>Koszt</span><strong>${p.seeds} nasion · ${p.water} wody</strong><span>Status</span><strong>${open ? (p.hybrid ? "hybryda" : "dostępna") : `od ${fmt(p.unlock || 0)} liści`}</strong></div><button data-plant="${p.id}" ${!open || free <= 0 || state.seeds < p.seeds || state.water < p.water ? "disabled" : ""}>Sadź</button></article>`; }).join("")}</div><h3 class="section-title">Posadzone</h3><div class="grid compact">${state.plants.map((p) => { const t = plantType(p.plantId); return `<article class="card"><div class="card-title"><span>${t.icon}</span><strong>${t.name}</strong><em>${Math.floor(p.growth * 100)}%</em></div><div class="mini-table"><span>Zdrowie</span><strong>${Math.round(p.health)}%</strong><span>Cecha</span><strong>${p.traits.growth}, ${p.traits.smell}</strong><span>Pokój</span><strong>${roomType(roomById(p.roomId)?.type)?.name || "?"}</strong></div></article>`; }).join("")}</div>`; }
  function renderCross() { panel.innerHTML = `<div class="panel-intro"><strong>Krzyżuj dojrzałe rośliny.</strong><span>Wymaga Krzyżówkarium, wody i pyłku. Odkryte hybrydy można później sadzić.</span></div><div class="grid">${RECIPES.map((r) => { const active = state.crossbreeds.find((c) => c.recipeId === r.id), result = plantType(r.result), ready = canCross(r); return `<article class="card ${state.discovered.includes(r.result) ? "is-bought" : ""}"><div class="card-title"><span>${r.icon}</span><strong>${result.name}</strong><em>${Math.round(r.chance * 100)}%</em></div><p>${r.parents.map((p) => plantType(p).name).join(" + ")} → ${result.name}</p><div class="mini-table"><span>Koszt</span><strong>${r.water} wody · ${r.pollen} pyłku</strong><span>Czas</span><strong>${active ? time(Math.max(0, r.seconds - (Date.now() - active.startedAt) / 1000)) : time(r.seconds)}</strong><span>Status</span><strong>${active ? "w toku" : ready ? "gotowe" : "braki"}</strong></div><button data-cross="${r.id}" ${!ready || active ? "disabled" : ""}>Krzyżuj</button></article>`; }).join("")}</div>`; }
  function renderGoats() { const m = meter || metrics(), active = state.goats.filter((g) => g.state !== "fleeing"); panel.innerHTML = `<div class="panel-intro"><strong>Kozy podgryzają liście.</strong><span>Kliknij kozę na canvasie albo przycisk SIO. Sowa krzyknie „SIO! SIO!” i koza ucieknie.</span></div><div class="data-table"><div><span>Aktywne</span><strong>${active.length}</strong></div><div><span>Ryzyko</span><strong>${Math.round(m.goatRisk * 100)}%</strong></div><div><span>Ochrona</span><strong>${Math.round(m.antiGoat * 100)}%</strong></div><div><span>Przegonione</span><strong>${fmt(state.stats.goatsScared)}</strong></div><div><span>Stracone liście</span><strong>${fmt(state.stats.goatLoss)}</strong></div></div><button class="danger-action" data-scare ${!active.length ? "disabled" : ""}>SIO! SIO!</button><div class="grid compact">${state.goats.length ? state.goats.map((g) => `<article class="card is-alert"><div class="card-title"><span>🐐</span><strong>Koza</strong><em>${Math.floor(g.age || 0)}s</em></div><p>Stan: ${g.state === "fleeing" ? "ucieka" : "podgryza"}.</p><button data-scare-id="${g.id}" ${g.state === "fleeing" ? "disabled" : ""}>SIO!</button></article>`).join("") : `<article class="card"><div class="card-title"><span>✨</span><strong>Spokój</strong><em>cute</em></div><p>Żadna koza nie podgryza liści.</p></article>`}</div>`; }
  function renderResearch() { const groups = [...new Set(RESEARCH.map((r) => r.branch))]; panel.innerHTML = `<div class="panel-intro"><strong>Badania dają długoterminowe cele.</strong><span>Produkcja, woda, antykozie taktyki, automatyzacja i offline progress.</span></div>${groups.map((g) => `<h3 class="section-title">${g}</h3><div class="grid compact">${RESEARCH.filter((r) => r.branch === g).map((r) => { const bought = hasResearch(r.id), req = (r.req || []).every(hasResearch); return `<article class="card ${bought ? "is-bought" : req ? "" : "is-locked"}"><div class="card-title"><span>${r.icon}</span><strong>${r.name}</strong><em>${bought ? "✓" : ""}</em></div><p>${r.desc}</p><div class="mini-table"><span>Koszt</span><strong>${costLabel(r.cost)}</strong><span>Status</span><strong>${bought ? "kupione" : req ? "dostępne" : "wymaga poprzednich"}</strong></div><button data-research="${r.id}" ${bought || !req || !canAfford(r.cost) ? "disabled" : ""}>Badaj</button></article>`; }).join("")}</div>`).join("")}`; }
  function renderStats() { const m = meter || metrics(), achievements = [["Pierwsza doniczka", "firstPlant"], ["Mała architektka", "rooms5"], ["SIO! SIO!", "sio"], ["Kozy mnie nie ruszają", "goats25"], ["Sowie Mendelki", "cross"], ["Hybryda!", "hybrid"], ["Szklarnia marzeń", "big"], ["Złote listki", "gold"]].map(([label, key]) => `<div><span>${label}</span><strong>${state.achievements[key] ? "✅" : "—"}</strong></div>`).join(""); panel.innerHTML = `<div class="panel-intro"><strong>Statystyki i zapis.</strong><span>Zapis lokalny: <code>${KEY}</code>.</span></div><div class="data-table"><div><span>Liście lifetime</span><strong>${fmt(state.lifetimeLeaves)}</strong></div><div><span>Najlepsze LPS</span><strong>${fmt(state.stats.bestLps)}/s</strong></div><div><span>Pokoje</span><strong>${state.rooms.length}</strong></div><div><span>Rośliny</span><strong>${state.plants.length}/${slots()}</strong></div><div><span>Krzyżowania</span><strong>${fmt(state.stats.crossbreeds)}</strong></div><div><span>Hybrydy</span><strong>${fmt(state.stats.hybrids)}</strong></div><div><span>Offline liście</span><strong>${fmt(state.stats.offlineLeaves)}</strong></div><div><span>Offline limit</span><strong>${time(m.cap)}</strong></div></div><div class="button-row"><button data-save>Zapisz teraz</button><button data-reset>Reset zapisu</button></div><h3 class="section-title">Osiągnięcia</h3><div class="data-table">${achievements}</div>`; }
  function renderHud() { const m = meter || metrics(), active = state.goats.filter((g) => g.state !== "fleeing").length; hud.leaves.textContent = fmt(state.leaves); hud.lps.textContent = `${fmt(m.lps)}/s`; hud.water.textContent = fmt(state.water); hud.seeds.textContent = fmt(state.seeds); hud.pollen.textContent = fmt(state.pollen); hud.goats.textContent = active ? `${active} aktywne` : `${Math.round(m.goatRisk * 100)}% ryz.`; hud.compost.textContent = fmt(state.compost); hud.joy.textContent = `${Math.round(state.owlJoy)}%`; $("waterAllButton").disabled = state.water < Math.max(8, Math.ceil(state.plants.length * 3)); $("sioButton").disabled = !active; }

  function resize() { const r = canvas.getBoundingClientRect(), dpr = Math.max(1, Math.min(2, devicePixelRatio || 1)); canvas.width = Math.max(320, Math.floor(r.width * dpr)); canvas.height = Math.max(280, Math.floor(r.height * dpr)); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }
  function rect() { const w = canvas.clientWidth, h = canvas.clientHeight, m = Math.min(34, w * .05); return { x: m, y: 38, w: w - m * 2, h: h - 76 }; }
  function draw() { const w = canvas.clientWidth, h = canvas.clientHeight, box = rect(); ctx.clearRect(0, 0, w, h); const bg = ctx.createLinearGradient(0, 0, w, h); bg.addColorStop(0, "#f7ffdf"); bg.addColorStop(.5, "#dff6ff"); bg.addColorStop(1, "#fff1f7"); ctx.fillStyle = bg; ctx.fillRect(0, 0, w, h); round(box.x, box.y, box.w, box.h, 28, "rgba(255,255,255,.58)", "rgba(80,120,95,.22)", 3); const cw = box.w / state.grid.columns, ch = box.h / state.grid.floors; for (let y = 0; y < state.grid.floors; y++) for (let x = 0; x < state.grid.columns; x++) { const room = state.rooms.find((r) => r.x === x && r.y === y), rx = box.x + x * cw + 6, ry = box.y + y * ch + 6; room ? drawRoom(room, rx, ry, cw - 12, ch - 12) : drawEmpty(rx, ry, cw - 12, ch - 12); } for (const p of state.plants) drawPlant(p, box, cw, ch); drawOwl(box, cw, ch); for (const g of state.goats) drawGoat(g, box, cw, ch); if (speech && speech.until > Date.now()) drawSpeech(speech.text, box.x + speech.x * box.w, box.y + speech.y * box.h); drawFloaters(w, h); }
  function drawRoom(room, x, y, w, h) { const t = roomType(room.type); round(x, y, w, h, 18, "rgba(255,255,255,.72)", "rgba(43,39,51,.12)", 2); ctx.fillStyle = "rgba(43,39,51,.72)"; ctx.font = "900 13px Trebuchet MS"; ctx.textAlign = "left"; ctx.fillText(t.name.slice(0, 15), x + 10, y + 20); ctx.textAlign = "right"; ctx.fillText(`★${room.level}`, x + w - 10, y + 20); ctx.textAlign = "center"; ctx.font = `${Math.min(30, h * .25)}px serif`; ctx.fillText(t.icon, x + w / 2, y + h * .58); }
  function drawEmpty(x, y, w, h) { ctx.save(); ctx.setLineDash([7, 7]); round(x, y, w, h, 16, "rgba(255,255,255,.25)", "rgba(83,130,93,.22)", 2); ctx.setLineDash([]); ctx.fillStyle = "rgba(83,130,93,.38)"; ctx.font = "900 22px Trebuchet MS"; ctx.textAlign = "center"; ctx.fillText("+", x + w / 2, y + h / 2 + 8); ctx.restore(); }
  function drawPlant(p, box, cw, ch) { const room = roomById(p.roomId), t = plantType(p.plantId); if (!room || !t) return; const siblings = plantsInRoom(room.id), idx = Math.max(0, siblings.findIndex((x) => x.uid === p.uid)), px = box.x + room.x * cw + cw * (.24 + (idx + .5) / Math.max(1, siblings.length) * .52), py = box.y + room.y * ch + ch * .78, s = .55 + p.growth * .65; ctx.save(); ctx.translate(px, py); ctx.scale(s, s); round(-12, 0, 24, 16, 5, "#d99a6c", "rgba(43,39,51,.14)", 1); ctx.fillStyle = t.color; ctx.globalAlpha = p.health < 35 ? .62 : 1; ctx.beginPath(); ctx.ellipse(-6, -9, 9, 16, -.6, 0, Math.PI * 2); ctx.ellipse(7, -12, 10, 18, .5, 0, Math.PI * 2); ctx.ellipse(0, -22, 8, 15, 0, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; if (p.growth < 1) { ctx.fillStyle = "rgba(255,255,255,.82)"; ctx.fillRect(-14, 20, 28, 5); ctx.fillStyle = "#4faf68"; ctx.fillRect(-14, 20, 28 * p.growth, 5); } ctx.restore(); }
  function drawOwl(box, cw, ch) { const g = state.goats.find((x) => x.state !== "fleeing"), room = g ? roomById(g.roomId) : state.rooms[Math.floor(Date.now() / 3000) % state.rooms.length] || state.rooms[0], x = box.x + (room.x + .18) * cw, y = box.y + (room.y + .65) * ch; ctx.save(); ctx.translate(x, y); ctx.fillStyle = "#8f6a4a"; ctx.beginPath(); ctx.ellipse(0, 0, 21, 26, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#f6d18b"; ctx.beginPath(); ctx.ellipse(0, 6, 14, 17, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "white"; ctx.beginPath(); ctx.arc(-8, -7, 7, 0, Math.PI * 2); ctx.arc(8, -7, 7, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#2b2733"; ctx.beginPath(); ctx.arc(-8, -7, 3, 0, Math.PI * 2); ctx.arc(8, -7, 3, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#ffd65a"; ctx.beginPath(); ctx.moveTo(0, -1); ctx.lineTo(-5, 6); ctx.lineTo(5, 6); ctx.closePath(); ctx.fill(); ctx.restore(); }
  function drawGoat(g, box, cw, ch) { const room = roomById(g.roomId) || state.rooms[0]; let x = box.x + (room.x + .76) * cw, y = box.y + (room.y + .68) * ch + Math.sin(Date.now() / 150) * 2; if (g.state === "fleeing") x += (1 - Math.max(0, g.fleeUntil - Date.now()) / 1050) * cw * .6; g.hit = { x: x - 26, y: y - 26, w: 56, h: 50 }; ctx.save(); ctx.translate(x, y); ctx.fillStyle = "#f4f0e6"; ctx.beginPath(); ctx.ellipse(0, 0, 22, 16, 0, 0, Math.PI * 2); ctx.ellipse(-16, -12, 13, 12, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#2b2733"; ctx.beginPath(); ctx.arc(-18, -13, 2.2, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#4faf68"; if (g.state === "nibbling") ctx.fillText("🍃", -34, -3); ctx.restore(); }
  function drawSpeech(text, x, y) { ctx.save(); ctx.font = "900 22px Trebuchet MS"; const w = ctx.measureText(text).width + 28; round(x - w / 2, y - 34, w, 34, 16, "rgba(255,255,255,.96)", "rgba(255,141,176,.55)", 2); ctx.fillStyle = "#2b2733"; ctx.textAlign = "center"; ctx.fillText(text, x, y - 10); ctx.restore(); }
  function round(x, y, w, h, r, fill, stroke, lw = 1) { ctx.beginPath(); ctx.moveTo(x + r, y); ctx.lineTo(x + w - r, y); ctx.quadraticCurveTo(x + w, y, x + w, y + r); ctx.lineTo(x + w, y + h - r); ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h); ctx.lineTo(x + r, y + h); ctx.quadraticCurveTo(x, y + h, x, y + h - r); ctx.lineTo(x, y + r); ctx.quadraticCurveTo(x, y, x + r, y); ctx.closePath(); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.stroke(); } }
  function pop(text, x, y, color) { texts.push({ text, x, y, color, life: 1 }); }
  function burst(x, y, count, color) { for (let i = 0; i < count; i++) particles.push({ x, y, vx: (Math.random() - .5) * .008, vy: Math.random() * -.007, size: 2 + Math.random() * 3, color, life: .45 + Math.random() * .55 }); }
  function drawFloaters(w, h) { particles = particles.filter((p) => p.life > 0); texts = texts.filter((t) => t.life > 0); for (const p of particles) { p.life -= .016; p.x += p.vx; p.y += p.vy; ctx.globalAlpha = Math.max(0, p.life); ctx.fillStyle = p.color; ctx.beginPath(); ctx.arc(p.x * w, p.y * h, p.size, 0, Math.PI * 2); ctx.fill(); } for (const t of texts) { t.life -= .016; t.y -= .0009; ctx.globalAlpha = Math.max(0, t.life); ctx.fillStyle = t.color; ctx.font = "900 17px Trebuchet MS"; ctx.textAlign = "center"; ctx.fillText(t.text, t.x * w, t.y * h); } ctx.globalAlpha = 1; }

  function handlePanel(e) { const b = e.target.closest("button"); if (!b) return; if (b.dataset.tab) { tab = b.dataset.tab; dirty = true; } else if (b.dataset.build) buildRoom(b.dataset.build); else if (b.dataset.upgrade) upgradeRoom(b.dataset.upgrade); else if (b.dataset.expand !== undefined) expandGrid(); else if (b.dataset.plant) plantSeed(b.dataset.plant); else if (b.dataset.cross) startCross(b.dataset.cross); else if (b.dataset.scare !== undefined) scareGoat(); else if (b.dataset.scareId) scareGoat(b.dataset.scareId); else if (b.dataset.research) buyResearch(b.dataset.research); else if (b.dataset.save !== undefined) save("manual"); else if (b.dataset.reset !== undefined) resetModal.hidden = false; }
  function canvasClick(e) { const r = canvas.getBoundingClientRect(), x = e.clientX - r.left, y = e.clientY - r.top, goat = state.goats.find((g) => g.state !== "fleeing" && g.hit && x >= g.hit.x && x <= g.hit.x + g.hit.w && y >= g.hit.y && y <= g.hit.y + g.hit.h); goat ? scareGoat(goat.id) : manualClick(); }
  function loop(now) { const delta = Math.min(.1, (now - last) / 1000 || 0); last = now; tick(delta); renderHud(); renderTimer += delta; if (dirty || renderTimer > 1) { render(); dirty = false; renderTimer = 0; } draw(); if (now % 7000 < 20) queueSave("auto"); requestAnimationFrame(loop); }
  function init() { resize(); addEventListener("resize", () => { resize(); dirty = true; }); canvas.addEventListener("click", canvasClick); tabs.addEventListener("click", handlePanel); panel.addEventListener("click", handlePanel); $("clickButton").addEventListener("click", manualClick); $("waterAllButton").addEventListener("click", () => waterAll(true)); $("sioButton").addEventListener("click", () => scareGoat()); $("offlineClose").addEventListener("click", () => offlineModal.hidden = true); $("resetCancel").addEventListener("click", () => resetModal.hidden = true); $("resetConfirm").addEventListener("click", () => { localStorage.removeItem(KEY); state = defaultSave(); resetModal.hidden = true; log("Szklarnia zaczęła od nowa."); dirty = true; save("manual"); }); offline(); log("Sowa sprawdza listki. Uważaj na kozy."); requestAnimationFrame(loop); }
  init();
})();
